apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feat-shark-111-appeals
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: feat-shark-111-appeals
    server: https://kubernetes.default.svc
  source:
    path: feat-shark-111-appeals
    repoURL: https://github.com/redadani-cohere/sandbox-manifest.git
    targetRevision: basic
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - Replace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
